### ISSUE TITLE
Conflict between EnderIO conduits and ChopdownUpdated

### ISSUE THREAD

**Issue by Guinaro** [Shovinus/ChopDownUpdated#19]
When using a Iron Pickaxe to remove an Energy Conduit and ChopdownUpdated installed and active I cannot remove the conduit. And get a nice error in the log. Even I am persistent about trying to remove it Minecraft eventually crashes when used in my modpack of ca 230 mods. Testing other conduits yield same unremovability.

I narrowed it down to a conflict between EnderIO and Chopdown with the bare essentials listed below

Minecraft version: 1.12.2
Forge: 14.23.4.2750
Mods:
Chop Down Update: 1.1.2
EnderCore 1.12.2-0.5.37
EnderIO 5.0.31
Just Enough Items: 4.12.0.215

Error in minecraft log:
```[Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.world.BlockEvent$BreakEvent@391314a4:
java.lang.NullPointerException: null
	at crazypants.enderio.conduits.conduit.BlockConduitBundle.getPickBlock(BlockConduitBundle.java:287) ~[BlockConduitBundle.class:?]
	at com.shovinus.chopdownupdated.tree.Tree.blockName(Tree.java:316) ~[Tree.class:?]
	at com.shovinus.chopdownupdated.tree.Tree.isWood(Tree.java:688) ~[Tree.class:?]
	at com.shovinus.chopdownupdated.ChopDown.onBlockBreak(ChopDown.java:69) ~[ChopDown.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_195_ChopDown_onBlockBreak_BreakEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:838) [ForgeHooks.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:283) [or.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180785_a(PlayerInteractionManager.java:244) [or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:702) [pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) [lp.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) [lp.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_171]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
[22:31:00] [Server thread/ERROR] [FML]: Index: 2 Listeners:
[22:31:00] [Server thread/ERROR] [FML]: 0: NORMAL
[22:31:00] [Server thread/ERROR] [FML]: 1: ASM: class crazypants.enderio.base.item.spawner.BrokenSpawnerHandler onBreakEvent(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[22:31:00] [Server thread/ERROR] [FML]: 2: ASM: com.shovinus.chopdownupdated.ChopDown@73e0637a onBlockBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[22:31:00] [Server thread/ERROR] [FML]: 3: ASM: class com.enderio.core.common.handlers.XPBoostHandler handleBlockBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[22:31:00] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_171]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
	at crazypants.enderio.conduits.conduit.BlockConduitBundle.getPickBlock(BlockConduitBundle.java:287) ~[BlockConduitBundle.class:?]
	at com.shovinus.chopdownupdated.tree.Tree.blockName(Tree.java:316) ~[Tree.class:?]
	at com.shovinus.chopdownupdated.tree.Tree.isWood(Tree.java:688) ~[Tree.class:?]
	at com.shovinus.chopdownupdated.ChopDown.onBlockBreak(ChopDown.java:69) ~[ChopDown.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_195_ChopDown_onBlockBreak_BreakEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:838) ~[ForgeHooks.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:283) ~[or.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180785_a(PlayerInteractionManager.java:244) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:702) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) ~[lp.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) ~[lp.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_171]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more```

**Comment by Shovinus** [comment]
He is probably using the obsolete method, I will wrap the function in a try or something

**Comment by esotericist** [comment]
I have a similar problem with the magneticraft feeding trough.

**Comment by Shovinus** [comment]
46eb24e9df11af20f230b1101590caed6b0e5837 Fixed
